-- Proyecto H² v2.4 · Sincronización integral con Supabase.
-- Ejecutar después de MIGRACION_V23.sql.
create table if not exists public.app_settings(id text primary key default 'global',value jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.sensor_definitions(id text primary key,device_id text references public.devices(id) on delete cascade,name text not null,sensor_type text not null,unit text not null default '',icon text not null default 'info',gpio integer,enabled boolean not null default true,metadata jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.actuator_definitions(id text primary key,device_id text references public.devices(id) on delete cascade,name text not null,actuator_type text not null,icon text not null default 'power',gpio integer,current_state boolean not null default false,enabled boolean not null default true,metadata jsonb not null default '{}',updated_at timestamptz not null default now());
alter table public.app_settings enable row level security;alter table public.sensor_definitions enable row level security;alter table public.actuator_definitions enable row level security;
drop policy if exists "settings read" on public.app_settings;drop policy if exists "settings manage" on public.app_settings;drop policy if exists "sensor definitions read" on public.sensor_definitions;drop policy if exists "sensor definitions manage" on public.sensor_definitions;drop policy if exists "actuator definitions read" on public.actuator_definitions;drop policy if exists "actuator definitions manage" on public.actuator_definitions;
create policy "settings read" on public.app_settings for select to authenticated using(true);create policy "settings manage" on public.app_settings for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "sensor definitions read" on public.sensor_definitions for select to authenticated using(true);create policy "sensor definitions manage" on public.sensor_definitions for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "actuator definitions read" on public.actuator_definitions for select to authenticated using(true);create policy "actuator definitions manage" on public.actuator_definitions for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
-- Permite al usuario actualizar sólo sus datos públicos; el cambio de rol se realiza mediante user-admin.
grant select on public.profiles,public.zones,public.devices,public.sensor_readings,public.actuator_events,public.notifications,public.team_members,public.role_permissions,public.audit_logs,public.app_settings,public.sensor_definitions,public.actuator_definitions to authenticated;
grant insert,update,delete on public.zones,public.devices,public.notifications,public.team_members,public.role_permissions,public.app_settings,public.sensor_definitions,public.actuator_definitions to authenticated;
grant insert on public.actuator_events,public.audit_logs to authenticated;
grant update(display_name,avatar_url,updated_at) on public.profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated,anon;
