-- Proyecto H² v2.3.0 · Ejecutar completo en Supabase SQL Editor.
create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum('superadmin','alumno','docente','ecociudadano'); exception when duplicate_object then null; end $$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique,display_name text not null default '',role public.app_role not null default 'ecociudadano',avatar_url text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.role_permissions(role public.app_role primary key,permissions text[] not null default '{}',description text not null default '',updated_at timestamptz not null default now());
insert into public.role_permissions(role,description,permissions) values
('superadmin','Control total del sistema.',array['dashboard','status','sensors','history','actuators','camera','devices','users','roles','notifications','profile','team','mqtt','settings','audit','remote_reset']),
('alumno','Aprendizaje, monitoreo y operación supervisada.',array['dashboard','status','sensors','history','actuators','camera','notifications','profile']),
('docente','Supervisión pedagógica y administración.',array['dashboard','status','sensors','history','actuators','camera','devices','users','notifications','profile','team','audit','remote_reset']),
('ecociudadano','Solo visualización del estado.',array['dashboard','status','sensors','camera']) on conflict(role) do update set description=excluded.description,permissions=excluded.permissions,updated_at=now();
create table if not exists public.zones(id uuid primary key default gen_random_uuid(),name text not null unique,created_at timestamptz not null default now());
insert into public.zones(name) values('Invernadero'),('Semillero'),('Cultivo vertical') on conflict do nothing;
create table if not exists public.devices(id text primary key check(id~'^ESP32-[0-9A-F]{4}$'),name text not null,zone_id uuid references public.zones(id) on delete set null,place_name text,address text,serial_number text,category text not null default 'ESP32-S3',latitude numeric(10,7),longitude numeric(10,7),ip_address inet,camera_url text,online boolean not null default false,wifi_percent smallint check(wifi_percent between 0 and 100),last_seen timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now());
alter table public.devices add column if not exists place_name text;alter table public.devices add column if not exists address text;alter table public.devices add column if not exists serial_number text;alter table public.devices add column if not exists category text not null default 'ESP32-S3';alter table public.devices add column if not exists latitude numeric(10,7);alter table public.devices add column if not exists longitude numeric(10,7);
create table if not exists public.sensor_readings(id bigint generated always as identity primary key,device_id text not null references public.devices(id) on delete cascade,sequence bigint not null,air_temperature real,humidity real,water_temperature real,ph real,tds_ppm real,wifi_rssi integer,uptime_ms bigint,actuators jsonb not null default '{}',created_at timestamptz not null default now(),unique(device_id,sequence));
create index if not exists readings_device_created_idx on public.sensor_readings(device_id,created_at desc);
create table if not exists public.actuator_events(id bigint generated always as identity primary key,device_id text references public.devices(id) on delete cascade,actuator text not null,state boolean not null,actor_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.notifications(id bigint generated always as identity primary key,title text not null,message text not null,level text not null default 'info',target_role public.app_role,read_by uuid[] not null default '{}',created_at timestamptz not null default now());
create table if not exists public.team_members(id uuid primary key default gen_random_uuid(),name text not null,team_role text not null,photo_url text,sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references auth.users(id) on delete set null,action text not null,entity text,entity_id text,details jsonb not null default '{}',created_at timestamptz not null default now());
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,display_name,role,avatar_url) values(new.id,coalesce(new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,''),'@',1)),'ecociudadano',new.raw_user_meta_data->>'avatar_url') on conflict(id) do update set display_name=coalesce(nullif(public.profiles.display_name,''),excluded.display_name),avatar_url=coalesce(public.profiles.avatar_url,excluded.avatar_url),updated_at=now();return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security;alter table public.role_permissions enable row level security;alter table public.zones enable row level security;alter table public.devices enable row level security;alter table public.sensor_readings enable row level security;alter table public.actuator_events enable row level security;alter table public.notifications enable row level security;alter table public.team_members enable row level security;alter table public.audit_logs enable row level security;
drop policy if exists "profiles select" on public.profiles;drop policy if exists "profile own update" on public.profiles;drop policy if exists "profiles admin update" on public.profiles;drop policy if exists "roles read" on public.role_permissions;drop policy if exists "roles superadmin write" on public.role_permissions;drop policy if exists "zones read" on public.zones;drop policy if exists "zones manage" on public.zones;drop policy if exists "devices read" on public.devices;drop policy if exists "devices manage" on public.devices;drop policy if exists "readings read" on public.sensor_readings;drop policy if exists "firmware readings insert" on public.sensor_readings;drop policy if exists "actuator events read" on public.actuator_events;drop policy if exists "actuator events write" on public.actuator_events;drop policy if exists "notifications read" on public.notifications;drop policy if exists "notifications manage" on public.notifications;drop policy if exists "team read" on public.team_members;drop policy if exists "team manage" on public.team_members;drop policy if exists "audit managers" on public.audit_logs;drop policy if exists "audit insert" on public.audit_logs;
create policy "profiles select" on public.profiles for select to authenticated using(id=auth.uid() or public.current_role() in('superadmin','docente'));
create policy "profile own update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "profiles admin update" on public.profiles for update to authenticated using(public.current_role()='superadmin') with check(public.current_role()='superadmin');
create policy "roles read" on public.role_permissions for select to authenticated using(true);
create policy "roles superadmin write" on public.role_permissions for all to authenticated using(public.current_role()='superadmin') with check(public.current_role()='superadmin');
create policy "zones read" on public.zones for select to authenticated using(true);create policy "zones manage" on public.zones for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "devices read" on public.devices for select to authenticated using(true);create policy "devices manage" on public.devices for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "readings read" on public.sensor_readings for select to authenticated using(true);create policy "firmware readings insert" on public.sensor_readings for insert to anon with check(true);
create policy "actuator events read" on public.actuator_events for select to authenticated using(true);create policy "actuator events write" on public.actuator_events for insert to authenticated with check(public.current_role() in('superadmin','docente','alumno'));
create policy "notifications read" on public.notifications for select to authenticated using(target_role is null or target_role=public.current_role());create policy "notifications manage" on public.notifications for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "team read" on public.team_members for select using(true);create policy "team manage" on public.team_members for all to authenticated using(public.current_role() in('superadmin','docente')) with check(public.current_role() in('superadmin','docente'));
create policy "audit managers" on public.audit_logs for select to authenticated using(public.current_role() in('superadmin','docente'));create policy "audit insert" on public.audit_logs for insert to authenticated with check(actor_id=auth.uid());
do $$begin alter publication supabase_realtime add table public.sensor_readings;exception when duplicate_object then null;end$$;
-- Después de crear el primer usuario, promoverlo una sola vez:
-- update public.profiles set role='superadmin' where id=(select id from auth.users where email='TU_EMAIL');
