[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@^6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = default.csv
lib_deps =
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.2.1
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.15
  milesburton/DallasTemperature@^3.11.0

